### ISSUE TITLE
Error in python script as well as error getting plugin data

### ISSUE THREAD

**Issue by Sharan123** [natko1412/repo.natko1412#6]
12:42:39.989 T:1159721728   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: (u'href',)
                                            Traceback (most recent call last):
                                              File "/home/osmc/.kodi/addons/plugin.video.nbafullgames/default.py", line 1037, in <module>
                                                play_game(game_link,game_name,game_img)
                                              File "/home/osmc/.kodi/addons/plugin.video.nbafullgames/default.py", line 412, in play_game
                                                parts=get_parts_from_game_link(game_link)
                                              File "/home/osmc/.kodi/addons/plugin.video.nbafullgames/default.py", line 244, in get_parts_from_game_link
                                                link=links[i]['href']
                                              File "/home/osmc/.kodi/addons/script.module.beautifulsoup/lib/BeautifulSoup.py", line 613, in __getitem__
                                                return self._getAttrMap()[key]
                                            KeyError: (u'href',)
                                            -->End of Python script error report<--
12:42:40.392 T:1926285824   ERROR: GetDirectory - Error getting plugin://plugin.video.nbafullgames/?foldername=Boston%20Celtics%20vs%20Sacramento%20Kings%20%20Mar%2025%2c%202018&img=http%3a%2f%2fnbahd.net%2fwp-content%2fuploads%2f2017%2$
12:42:40.394 T:1926285824   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.nbafullgames/?foldername=Boston%20Celtics%20vs%20Sacramento%20Kings%20%20Mar%2025%2c%202018&img=http%3a%2f%2fnbahd.net%2fwp-content%2fuploads%2f2017%$

I dont know if its some kinda dependancy issue but if it is should be noted what dependancy should be installed (or included in the zip file)

**Comment by cyberkid2002** [comment]
Did you ever get this sorted?  Would love to use this plugin again...
